module.exports = {
  'views/app/app.ftl': require('./views/app/app.ftl.js'),
  'source/entries/app/app.js': require('./source/entries/app/app.js'),
  'source/pages/App/components/index.js': require('./source/pages/App/components/index.js'),
  'source/pages/App/reducers/initialState.js': require('./source/pages/App/reducers/initialState.js'),
  'source/pages/App/reducers/reducer.js': require('./source/pages/App/reducers/reducer.js'),
  'source/pages/App/reducers/rootReducer.js': require('./source/pages/App/reducers/rootReducer.js'),
  'source/pages/App/actions.js': require('./source/pages/App/actions.js'),
  'source/pages/App/actionTypes.js': require('./source/pages/App/actionTypes.js'),
  'source/pages/App/index.js': require('./source/pages/App/index.js'),
  'source/pages/App/App.js': require('./source/pages/App/App.js'),
  'source/pages/App/App.less': require('./source/pages/App/App.less.js'),
  'source/pages/App/routes.js': require('./source/pages/App/routes.js'),
  'source/pages/App/view.js': require('./source/pages/App/view.js'),
};