module.exports = {
  'views/{{PageName}}/{{PageName}}.ftl': require('./views/app/app.ftl.js'),
  'source/pages/{{PageName}}/entry.js': require('./source/pages/App/entry.js'),
  'source/pages/{{PageName}}/components/index.js': require('./source/pages/App/components/index.js'),
  'source/pages/{{PageName}}/reducers/initialState.js': require('./source/pages/App/reducers/initialState.js'),
  'source/pages/{{PageName}}/reducers/reducer.js': require('./source/pages/App/reducers/reducer.js'),
  'source/pages/{{PageName}}/reducers/rootReducer.js': require('./source/pages/App/reducers/rootReducer.js'),
  'source/pages/{{PageName}}/actions.js': require('./source/pages/App/actions.js'),
  'source/pages/{{PageName}}/actionTypes.js': require('./source/pages/App/actionTypes.js'),
  'source/pages/{{PageName}}/index.js': require('./source/pages/App/index.js'),
  'source/pages/{{PageName}}/App.js': require('./source/pages/App/App.js'),
  'source/pages/{{PageName}}/App.less': require('./source/pages/App/App.less.js'),
  'source/pages/{{PageName}}/routes.js': require('./source/pages/App/routes.js'),
  'source/pages/{{PageName}}/view.js': require('./source/pages/App/view.js'),
};
